language: android
sudo: required
jdk: oraclejdk8

addons:
  apt_packages:
    - pandoc

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-28
    - android-24
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"

script:
  - ./gradlew clean check --profile
  - pandoc `ls -1rt build/reports/profile/profile-*.html | tail -n1` -t plain
