site_name: Mavionics flight data
site_description: 'Mavionics documentation'
site_author: 'Alexander Poole'
site_url: 'https://Mavionics.github.io/flightData/'

# Repository
repo_name: 'mavionics/flightData'
repo_url: 'https://github.com/Mavionics/flightData'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Alexander Poole'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/Mavionics'
